parameters:
    openium_symfony_toolkit.public_dir: '%kernel.project_dir%/public'
    openium_symfony_toolkit.uploads_dir_name: 'uploads'
    openium_symfony_toolkit.kernel_exception_listener_enable: true
    openium_symfony_toolkit.kernel_exception_listener_path: '/api'
    openium_symfony_toolkit.kernel_exception_listener_class: 'Openium\SymfonyToolKitBundle\EventListener\PathKernelExceptionListener'

services:

    openium_symfony_toolkit.file_uploader:
        class: Openium\SymfonyToolKitBundle\Service\FileUploaderService
        arguments:
            - '%openium_symfony_toolkit.public_dir%'
            - '%openium_symfony_toolkit.uploads_dir_name%'
        public: true

    openium_symfony_toolkit.exception_format:
        class: Openium\SymfonyToolKitBundle\Service\ExceptionFormatService
        arguments:
            - '@kernel'
        public: true

    openium_symfony_toolkit.doctrine_exception_handler:
        class: Openium\SymfonyToolKitBundle\Service\DoctrineExceptionHandlerService
        arguments:
            - '@monolog.logger'
        public: true

    openium_symfony_toolkit.server:
        class: Openium\SymfonyToolKitBundle\Service\ServerService
        arguments:
            - '@request_stack'
        public: true

    openium_symfony_toolkit.at_helper:
        class: Openium\SymfonyToolKitBundle\Service\AtHelper
        arguments:
            - '@monolog.logger'
        public: true

    openium_symfony_toolkit.kernel_exception_listener:
        class: '%openium_symfony_toolkit.kernel_exception_listener_class%'
        arguments:
            - '@openium_symfony_toolkit.exception_format'
            - '%openium_symfony_toolkit.kernel_exception_listener_path%'
            - '%openium_symfony_toolkit.kernel_exception_listener_enable%'
            - '@monolog.logger'
        public: false
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
