parameters:

    openium_symfony_toolkit.public_dir: '%kernel.project_dir%/public'
    openium_symfony_toolkit.uploads_dir_name: 'uploads'

services:

    openium_symfony_toolkit.file_uploader:
        class: Openium\SymfonyToolKitBundle\Service\FileUploaderService
        arguments:
            - '%openium_symfony_toolkit.public_dir%'
            - '%openium_symfony_toolkit.uploads_dir_name%'
        public: true

    openium_symfony_toolkit.exception_format:
        class: Openium\SymfonyToolKitBundle\Service\ExceptionFormatService
        arguments:
            - '@kernel'
        public: true

    openium_symfony_toolkit.doctrine_exception_handler:
        class: Openium\SymfonyToolKitBundle\Service\DoctrineExceptionHandlerService
        arguments:
            - '@monolog.logger'
        public: true

    openium_symfony_toolkit.server:
        class: Openium\SymfonyToolKitBundle\Service\ServerService
        arguments:
            - '@request_stack'
        public: true